services:
  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
